trigger:
- dev
- master
 
variables:
  imageName: 'azure-node-mini'
  devAcrLoginServer: 'azureminidev.azurecr.io'
  prodAcrLoginServer: 'azureminiacr.azurecr.io'
 
stages:
 
# ------------------------
# Stage 1: Build Image
# ------------------------
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
 
    # Build & push to DEV ACR when branch = dev
    - task: Docker@2
      displayName: Build & Push image to DEV ACR
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
      inputs:
        command: buildAndPush
        containerRegistry: 'azureacr_minidev'      # Docker registry connection (DEV)
        repository: '$(imageName)'
        dockerfile: '**/Dockerfile'
        tags: |
          latest
 
    # Build & push to PROD ACR when branch = master
    - task: Docker@2
      displayName: Build & Push image to PROD ACR
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      inputs:
        command: buildAndPush
        containerRegistry: 'azureacr_mini'         # Docker registry connection (PROD)
        repository: '$(imageName)'
        dockerfile: '**/Dockerfile'
        tags: |
          latest
 
# ------------------------
# Stage 2: Deploy to DEV (only when branch = dev)
# ------------------------
- stage: DeployDev
  displayName: Deploy to DEV Environment
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  jobs:
  - deployment: DeployDevJob
    displayName: Deploy to DEV
    environment: dev
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy DEV Container
            inputs:
              azureSubscription: 'AzureServiceConnectionNew'           # AzureRM connection
              appName: 'azure-mini-webapp-dev'
              containers: '$(devAcrLoginServer)/$(imageName):latest'
 
# ------------------------
# Stage 3: Deploy to PROD (only when branch = master)
# ------------------------
- stage: DeployProd
  displayName: Deploy to PRODUCTION Environment
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: DeployProdJob
    displayName: Deploy to PRODUCTION
    environment: production
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy PROD Container
            inputs:
              azureSubscription: 'AzureServiceConnectionNew'           # same AzureRM connection
              appName: 'azure-mini-webapp'
              containers: '$(prodAcrLoginServer)/$(imageName):latest'
