trigger:
- master

variables:
  imageName: 'azure-node-mini'
  acrLoginServer: 'azureminiacr.azurecr.io'

stages:

# ------------------------
# Stage 1: Build & Push
# ------------------------
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push Image to ACR
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        command: buildAndPush
        repository: '$(imageName)'
        dockerfile: '**/Dockerfile'
        containerRegistry: 'azureacr_mini'
        tags: |
          latest


# ------------------------
# Stage 2: Deploy to App Service (with Approvals)
# ------------------------
- stage: Deploy
  displayName: Deploy to Azure App Service
  dependsOn: Build
  jobs:
  - deployment: DeployToProd
    displayName: Deploy to Production
    environment: 'production'       # <-- This connects to your approval gate
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy Container to App Service
            inputs:
              azureSubscription: 'AzureServiceConnection'
              appName: 'azure-mini-webapp'
              containers: 'azureminiacr.azurecr.io/azure-node-mini:latest'

