trigger:
- dev
- master
 
variables:
  imageName: 'azure-node-mini'
  devAcrLoginServer: 'azureminidev.azurecr.io'
  prodAcrLoginServer: 'azureminiacr.azurecr.io'
 
stages:
 
# ------------------------
# Stage 1: Build Image
# ------------------------
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
 
    steps:
    - checkout: self
 
    # Build & push image to ACR based on branch
    - task: Docker@2
      displayName: Build & Push image to DEV ACR
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
      inputs:
        command: buildAndPush
        containerRegistry: 'azureacr_minidev'             # <-- Dev ACR service connection
        repository: '$(imageName)'
        dockerfile: '**/Dockerfile'
        tags: |
          latest
 
    - task: Docker@2
      displayName: Build & Push image to PROD ACR
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      inputs:
        command: buildAndPush
        containerRegistry: 'azureacr_mini'            # <-- Prod ACR service connection
        repository: '$(imageName)'
        dockerfile: '**/Dockerfile'
        tags: |
          latest
 
# ------------------------
# Stage 2: Deploy to DEV (branch = dev)
# ------------------------
- stage: DeployDev
  displayName: Deploy to DEV Environment
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  jobs:
  - deployment: DeployDevJob
    displayName: Deploy to DEV
    environment: dev
    pool:
      vmImage: 'ubuntu-latest'
 
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy DEV Container
            inputs:
              azureSubscription: 'azureacr_minidev'  # <-- Dev app service connection
              appName: 'azure-mini-webapp-dev'
              containers: 'azureminidev.azurecr.io/azure-node-mini:latest'
 
# ------------------------
# Stage 3: Deploy to PROD (branch = master)
# ------------------------
- stage: DeployProd
  displayName: Deploy to PRODUCTION Environment
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: DeployProdJob
    displayName: Deploy to PRODUCTION
    environment: production
    pool:
      vmImage: 'ubuntu-latest'
 
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy PROD Container
            inputs:
              azureSubscription: 'AzureServiceConnection-Prod'  # <-- Prod app service connection
              appName: 'azure-mini-webapp'
              containers: 'azureminiacr.azurecr.io/azure-node-mini:latest'

