trigger:
- master

variables:
  imageName: 'azure-node-mini'
  acrLoginServer: 'azureminiacr.azurecr.io'

stages:

# ------------------------
# Stage 1: Build Image
# ------------------------
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        command: buildAndPush
        repository: '$(imageName)'
        dockerfile: '**/Dockerfile'
        containerRegistry: 'azureacr_mini'
        tags: |
          latest

# ------------------------
# Stage 2: Deploy to DEV
# ------------------------
- stage: DeployDev
  displayName: Deploy to DEV Environment
  dependsOn: Build
  jobs:
  - deployment: DeployDevJob
    displayName: Deploy to DEV
    environment: dev
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'AzureServiceConnection'
              appName: 'azure-mini-webapp'
              containers: 'azureminiacr.azurecr.io/azure-node-mini:latest'

# ------------------------
# Stage 3: Deploy to STAGE
# ------------------------
- stage: DeployStage
  displayName: Deploy to STAGE Environment
  dependsOn: DeployDev
  jobs:
  - deployment: DeployStageJob
    displayName: Deploy to STAGE
    environment: stage
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'AzureServiceConnection'
              appName: 'azure-mini-webapp'
              containers: 'azureminiacr.azurecr.io/azure-node-mini:latest'

# ------------------------
# Stage 4: Deploy to PROD
# ------------------------
- stage: DeployProd
  displayName: Deploy to PRODUCTION Environment
  dependsOn: DeployStage
  jobs:
  - deployment: DeployProdJob
    displayName: Deploy to PRODUCTION
    environment: production   # Approval required here
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'AzureServiceConnection'
              appName: 'azure-mini-webapp'
              containers: 'azureminiacr.azurecr.io/azure-node-mini:latest'
